name: Build crust-box-home (main)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.FOR_DOCKER }}

      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/decooio/crust-box-home:latest, ghcr.io/decooio/crust-box-home:${{ steps.date.outputs.date }}
          # tags: ghcr.io/decooio/crust-box-cloud:latest, ghcr.io/decooio/crust-box-cloud:${{ steps.date.outputs.date }}, gavfu/crust-box-cloud:latest, gavfu/crust-box-cloud:${{ steps.date.outputs.date }}
